<#
    RebrandX installer for Windows.

    Wires the app into the Start menu, the PATH and Explorer's right-click
    menu. Everything it touches is per-user: no admin rights, no Program
    Files, nothing outside HKCU and %LOCALAPPDATA%.

        powershell -ExecutionPolicy Bypass -File install.ps1

    Options:
        -NoDesktopIcon    skip the desktop shortcut
        -NoContextMenu    skip the "Rebrand with RebrandX" Explorer entry
        -NoPath           do not add the commands to PATH
        -DryRun           report what would change and write nothing
#>
[CmdletBinding()]
param(
    [switch]$NoDesktopIcon,
    [switch]$NoContextMenu,
    [switch]$NoPath,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
$BinDir = Join-Path $env:LOCALAPPDATA "RebrandX\bin"
$IconSrc = Join-Path $Root "share\rebrandx.ico"
$RegKey = "HKCU:\Software\Classes\Directory\shell\RebrandX"
$RegKeyBg = "HKCU:\Software\Classes\Directory\Background\shell\RebrandX"

function Say($msg) { Write-Host "  $msg" }

# Every write goes through this, so -DryRun genuinely cannot touch the
# machine -- the same rule the app itself follows.
function Change([string]$label, [scriptblock]$action) {
    if ($DryRun) { Write-Host "  would: $label" -ForegroundColor DarkGray; return }
    & $action
    Say $label
}

# Windows PowerShell turns anything an .exe writes to stderr into an
# ErrorRecord, which $ErrorActionPreference = "Stop" then treats as fatal --
# so a native command that merely printed a warning would abort the install.
# Everything external goes through here instead.
function Invoke-Native {
    param([string]$Exe, [string[]]$Arguments)
    $old = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $out = & $Exe @Arguments 2>&1
        return [pscustomobject]@{
            Code   = $LASTEXITCODE
            Output = ($out | Out-String).Trim()
        }
    } finally {
        $ErrorActionPreference = $old
    }
}

if ($DryRun) {
    Write-Host "Dry run - nothing will be written" -ForegroundColor Yellow
}
Write-Host "Installing RebrandX from $Root" -ForegroundColor Cyan

# --- find Python ----------------------------------------------------------
# The py launcher is what the python.org installer registers, and it works
# whether or not the user ticked "Add Python to PATH".
$PyExe = $null
$PywExe = $null
foreach ($cand in @("py", "python")) {
    $cmd = Get-Command $cand -ErrorAction SilentlyContinue
    if ($cmd) {
        $probe = Invoke-Native $cmd.Source @("-c", "import sys; print(sys.executable)")
        if ($probe.Code -eq 0 -and $probe.Output) { $PyExe = $probe.Output; break }
    }
}
if (-not $PyExe) {
    Write-Host ""
    Write-Host "Python 3.8 or newer was not found." -ForegroundColor Red
    Write-Host "Install it from https://www.python.org/downloads/ and tick"
    Write-Host '"Add Python to PATH" during setup, then run this again.'
    exit 1
}
$ver = (Invoke-Native $PyExe @("-c", "import sys; print('%d.%d' % sys.version_info[:2])")).Output
Say "python    -> $PyExe ($ver)"

# pythonw.exe runs the window with no console behind it.
$PywExe = Join-Path (Split-Path -Parent $PyExe) "pythonw.exe"
if (-not (Test-Path $PywExe)) { $PywExe = $PyExe }

# --- check tkinter --------------------------------------------------------
# The window is built on tkinter, which is part of the standard library on
# Windows. There is nothing to install -- but a stripped or embedded Python
# can be missing it, and that is worth saying plainly rather than letting
# the app fail on launch.
$tk = Invoke-Native $PyExe @("-c", "import tkinter; print(tkinter.TkVersion)")
if ($tk.Code -eq 0) {
    Say "tkinter   -> OK (Tk $($tk.Output))"
} else {
    Write-Host ""
    Write-Host "This Python has no tkinter, so the window cannot open." -ForegroundColor Red
    Write-Host "Reinstall Python from python.org with the default options"
    Write-Host "(the 'tcl/tk and IDLE' component must be ticked)."
    Write-Host ""
    Write-Host "The command line works without it: rbx OldName NewName PATH"
    exit 1
}

# --- command shims on PATH ------------------------------------------------
$rbxCmd = @"
@echo off
REM RebrandX command line. Generated by install.ps1 -- edit the repo, not this.
"$PyExe" "$Root\rebrandx\cli.py" %*
exit /b %ERRORLEVEL%
"@

$appCmd = @"
@echo off
REM RebrandX window. Generated by install.ps1 -- edit the repo, not this.
start "" "$PywExe" "$Root\rebrandx\app_tk.py" %*
"@

Change "commands  -> $BinDir\rbx.cmd, rebrandx.cmd" {
    New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
    Set-Content -Path (Join-Path $BinDir "rbx.cmd") -Value $rbxCmd -Encoding ASCII
    Set-Content -Path (Join-Path $BinDir "rebrandx.cmd") -Value $appCmd -Encoding ASCII
}

if (-not $NoPath) {
    # Go through the registry rather than [Environment]::SetEnvironmentVariable:
    # that call rewrites the value as a plain string, which would expand and
    # freeze any %VAR% another program has in its PATH entry.
    $key = "HKCU:\Environment"
    $current = (Get-ItemProperty -Path $key -Name Path -ErrorAction SilentlyContinue).Path
    if (-not $current) { $current = "" }
    $parts = $current -split ";" | Where-Object { $_ -ne "" }
    if ($parts -notcontains $BinDir) {
        Change "PATH      -> added $BinDir (open a new terminal to pick it up)" {
            $new = (@($parts) + $BinDir) -join ";"
            $kind = "String"
            if ($new -match "%") { $kind = "ExpandString" }
            Set-ItemProperty -Path $key -Name Path -Value $new -Type $kind

            # Tell running shells and Explorer that the environment moved.
            if (-not ("Win32.NativeMethods" -as [type])) {
                Add-Type -Namespace Win32 -Name NativeMethods -MemberDefinition @"
[DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam,
    string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
"@
            }
            $result = [UIntPtr]::Zero
            [Win32.NativeMethods]::SendMessageTimeout(
                [IntPtr]0xffff, 0x1A, [UIntPtr]::Zero, "Environment", 2, 5000, [ref]$result) | Out-Null
        }
    } else {
        Say "PATH      -> already contains $BinDir"
    }
}

# --- shortcuts ------------------------------------------------------------
function New-Shortcut($linkPath, $target, $arguments, $icon, $desc) {
    $shell = New-Object -ComObject WScript.Shell
    $sc = $shell.CreateShortcut($linkPath)
    $sc.TargetPath = $target
    $sc.Arguments = $arguments
    $sc.WorkingDirectory = Split-Path -Parent $target
    $sc.Description = $desc
    if ($icon -and (Test-Path $icon)) { $sc.IconLocation = $icon }
    $sc.Save()
    [Runtime.InteropServices.Marshal]::ReleaseComObject($shell) | Out-Null
}

$appPy = Join-Path $Root "rebrandx\app_tk.py"
$startMenu = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs"
Change "start menu-> RebrandX" {
    New-Item -ItemType Directory -Force -Path $startMenu | Out-Null
    New-Shortcut (Join-Path $startMenu "RebrandX.lnk") $PywExe "`"$appPy`"" $IconSrc `
        "Replace a project name across a folder's files, names and contents"
}

$desktop = [Environment]::GetFolderPath("Desktop")
$desktopLink = Join-Path $desktop "RebrandX.lnk"
if ($NoDesktopIcon) {
    Change "desktop   -> skipped (-NoDesktopIcon)" {
        Remove-Item $desktopLink -ErrorAction SilentlyContinue
    }
} elseif (Test-Path $desktop) {
    Change "desktop   -> $desktopLink" {
        New-Shortcut $desktopLink $PywExe "`"$appPy`"" $IconSrc "Rebrand a project folder"
    }
}

# --- Explorer right-click --------------------------------------------------
if (-not $NoContextMenu) {
    # %V is the folder that was clicked -- for a right-click on a folder and
    # for a right-click on the background of an open one alike.
    Change "explorer  -> right-click a folder > Rebrand with RebrandX" {
        foreach ($k in @($RegKey, $RegKeyBg)) {
            New-Item -Path $k -Force | Out-Null
            Set-ItemProperty -Path $k -Name "(default)" -Value "Rebrand with RebrandX"
            if (Test-Path $IconSrc) { Set-ItemProperty -Path $k -Name "Icon" -Value $IconSrc }
            New-Item -Path "$k\command" -Force | Out-Null
            Set-ItemProperty -Path "$k\command" -Name "(default)" `
                -Value "`"$PywExe`" `"$appPy`" `"%V`""
        }
    }
}

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host ""
Write-Host "  Launch it        : Start menu > RebrandX"
Write-Host "  Right-click menu : right-click any folder > Rebrand with RebrandX"
Write-Host "  Terminal         : rbx OldName NewName C:\path\to\folder"
Write-Host ""
Write-Host "  Remove it later  : powershell -ExecutionPolicy Bypass -File uninstall.ps1"
